[project]
name = "galis"
version = "0.1.0"
description = ""
authors = [
    {name = "Perunio",email = "divodar@protonmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff (>=0.12.2,<0.13.0)",
    "pytest (>=8.4.1,<9.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
